baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "Docdock"
theme = "/hugo/docs/themes/docdock"
themesdir = "../.."

[params]
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = false # default is false
# themeStyle = "theme" # overide base css
themeVariant = "pulse" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3> //// </h3>"
name = "<i class='fa fa-heartbeat'></i> IST Research"
identifier = "ds"
url = "http://istresearch.com/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-camera'></i> Showcases"
url = "/showcase"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-heart'></i> Credits"
url = "/credits"
weight = 30
